In [27]:
import pandas as pd
from src.config import Config

In [28]:
df=pd.read_csv('music_data.csv')
df

,Unnamed: 0,artist,album,units_sold,month,year
0,0,The Midnight Echoes,Neon Dreams,1200.0,May,2023
1,1,Electric Dreams,Synthwave Memories,850.0,March,2022
2,2,Soulful Strings,Harmony in Blue,1500.0,July,2023
3,3,Urban Beats,City Pulse,980.0,January,2021
4,4,Pop Vortex,Dancing in the Light,2450.0,September,2023
...,...,...,...,...,...,...
994,994,Desert Drifters,Winds of Sand,360.0,September,2024
995,995,Quantum Beats,Timeless Rhythms,160.0,October,2024
996,996,Frostbite Echoes,Winter Whispers,230.0,November,2024
997,997,The Midnight Echoes,Echoes of the Past,315.0,December,2024
998,998,Electric Dreams,Neon Skies,400.0,January,2025

In [29]:
df=df.drop('Unnamed: 0',axis=1)
df

                  artist                 album  units_sold      month  year
0    The Midnight Echoes           Neon Dreams      1200.0        May  2023
1        Electric Dreams    Synthwave Memories       850.0      March  2022
2        Soulful Strings       Harmony in Blue      1500.0       July  2023
3            Urban Beats            City Pulse       980.0    January  2021
4             Pop Vortex  Dancing in the Light      2450.0  September  2023
..                   ...                   ...         ...        ...   ...
994      Desert Drifters         Winds of Sand       360.0  September  2024
995        Quantum Beats      Timeless Rhythms       160.0    October  2024
996     Frostbite Echoes       Winter Whispers       230.0   November  2024
997  The Midnight Echoes    Echoes of the Past       315.0   December  2024
998      Electric Dreams            Neon Skies       400.0    January  2025

[999 rows x 5 columns]

In [ ]:
from src.preprocessor import document_generator,create_embeddings
documents=document_generator(df)
embeddings=create_embeddings(documents)

Batches: 100%|██████████| 32/32 [00:03<00:00,  9.33it/s]

In [31]:
from src.vector_store import VectorStore
db=VectorStore(Config.collection_name)
db.add_documents(documents,embeddings)
db.count()

999

In [38]:
from src.retriever import Retriever
retriever=Retriever(db)
results=retriever.search("Which album was made by Soulful Strings")

In [41]:
for doc,dist in zip(
    results['documents'][0],
    results['distances'][0]):
    print(dist)
    print(doc)

0.4572600722312927
artist:Soulful Strings
album:Strings of Life
units_sold:279.0
month:June
year:2023

0.466275155544281
artist:Soulful Strings
album:Harmony in Red
units_sold:420.0
month:February
year:2024

0.4794216752052307
artist:Soulful Strings
album:Harmony in Blue
units_sold:1500.0
month:July
year:2023

0.47958916425704956
artist:Soulful Strings
album:Strings of Passion
units_sold:1500.0
month:August
year:2023

0.48077210783958435
artist:Soulful Strings
album:Harmony Lane
units_sold:260.0
month:February
year:2024

In [36]:
from src.rag import RAG
rag=RAG(db)
rag.ask("which artist sold the most albums?")

{'question': 'which artist sold the most albums?',
 'context': 'artist:Urban Beats\nalbum:City Pulse\nunits_sold:2100.0\nmonth:May\nyear:2023\n\n\nartist:Urban Beats\nalbum:City Pulse\nunits_sold:156.0\nmonth:May\nyear:2023\n\n\nartist:Urban Pulse\nalbum:City Beats\nunits_sold:4100.0\nmonth:May\nyear:2023\n\n\nartist:Urban Pulse\nalbum:City Beats\nunits_sold:295.0\nmonth:May\nyear:2022\n\n\nartist:Urban Pulse\nalbum:City Beats\nunits_sold:1350.0\nmonth:April\nyear:2023\n',
 'answer': 'Answer: Urban Pulse'}