In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('music_data.csv')
df

,Unnamed: 0,artist,album,units_sold,month,year
0,0,The Midnight Echoes,Neon Dreams,1200.0,May,2023
1,1,Electric Dreams,Synthwave Memories,850.0,March,2022
2,2,Soulful Strings,Harmony in Blue,1500.0,July,2023
3,3,Urban Beats,City Pulse,980.0,January,2021
4,4,Pop Vortex,Dancing in the Light,2450.0,September,2023
...,...,...,...,...,...,...
994,994,Desert Drifters,Winds of Sand,360.0,September,2024
995,995,Quantum Beats,Timeless Rhythms,160.0,October,2024
996,996,Frostbite Echoes,Winter Whispers,230.0,November,2024
997,997,The Midnight Echoes,Echoes of the Past,315.0,December,2024
998,998,Electric Dreams,Neon Skies,400.0,January,2025

In [3]:
df=df.drop('Unnamed: 0',axis=1)
df

                  artist                 album  units_sold      month  year
0    The Midnight Echoes           Neon Dreams      1200.0        May  2023
1        Electric Dreams    Synthwave Memories       850.0      March  2022
2        Soulful Strings       Harmony in Blue      1500.0       July  2023
3            Urban Beats            City Pulse       980.0    January  2021
4             Pop Vortex  Dancing in the Light      2450.0  September  2023
..                   ...                   ...         ...        ...   ...
994      Desert Drifters         Winds of Sand       360.0  September  2024
995        Quantum Beats      Timeless Rhythms       160.0    October  2024
996     Frostbite Echoes       Winter Whispers       230.0   November  2024
997  The Midnight Echoes    Echoes of the Past       315.0   December  2024
998      Electric Dreams            Neon Skies       400.0    January  2025

[999 rows x 5 columns]

In [5]:
from preprocessor import document_generator, create_embeddings
documents=document_generator(df)
embeddings=create_embeddings(documents)

Batches: 100%|██████████| 32/32 [00:03<00:00,  8.03it/s]