In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('music_data.csv')
df

,Unnamed: 0,artist,album,units_sold,month,year
0,0,The Midnight Echoes,Neon Dreams,1200.0,May,2023
1,1,Electric Dreams,Synthwave Memories,850.0,March,2022
2,2,Soulful Strings,Harmony in Blue,1500.0,July,2023
3,3,Urban Beats,City Pulse,980.0,January,2021
4,4,Pop Vortex,Dancing in the Light,2450.0,September,2023
...,...,...,...,...,...,...
994,994,Desert Drifters,Winds of Sand,360.0,September,2024
995,995,Quantum Beats,Timeless Rhythms,160.0,October,2024
996,996,Frostbite Echoes,Winter Whispers,230.0,November,2024
997,997,The Midnight Echoes,Echoes of the Past,315.0,December,2024
998,998,Electric Dreams,Neon Skies,400.0,January,2025

In [3]:
df=df.drop('Unnamed: 0',axis=1)
df

                  artist                 album  units_sold      month  year
0    The Midnight Echoes           Neon Dreams      1200.0        May  2023
1        Electric Dreams    Synthwave Memories       850.0      March  2022
2        Soulful Strings       Harmony in Blue      1500.0       July  2023
3            Urban Beats            City Pulse       980.0    January  2021
4             Pop Vortex  Dancing in the Light      2450.0  September  2023
..                   ...                   ...         ...        ...   ...
994      Desert Drifters         Winds of Sand       360.0  September  2024
995        Quantum Beats      Timeless Rhythms       160.0    October  2024
996     Frostbite Echoes       Winter Whispers       230.0   November  2024
997  The Midnight Echoes    Echoes of the Past       315.0   December  2024
998      Electric Dreams            Neon Skies       400.0    January  2025

[999 rows x 5 columns]

In [4]:
from src.preprocessor import document_generator, create_embeddings
documents=document_generator(df)
embeddings=create_embeddings(documents)

c:\Users\Aman\anaconda3\envs\qwen\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8864.53it/s]
Batches: 100%|██████████| 32/32 [00:03<00:00,  9.36it/s]

In [5]:
from src.vector_store import VectorStore
db=VectorStore(collection_name="music_sales")
db.add_documents(documents,embeddings)
db.count()

999

In [6]:
from src.retriever import Retriever
retriever=Retriever(db)
results=retriever.search("Which album was made by Soulful Strings")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7053.30it/s]

In [7]:
results['documents'][0]

['artist:Soulful Strings\nalbum:Strings of Life\nunits_sold:279.0\nmonth:June\nyear:2023\n',
 'artist:Soulful Strings\nalbum:Harmony in Red\nunits_sold:420.0\nmonth:February\nyear:2024\n',
 'artist:Soulful Strings\nalbum:Harmony in Blue\nunits_sold:1500.0\nmonth:July\nyear:2023\n',
 'artist:Soulful Strings\nalbum:Strings of Passion\nunits_sold:1500.0\nmonth:August\nyear:2023\n',
 'artist:Soulful Strings\nalbum:Harmony Lane\nunits_sold:260.0\nmonth:February\nyear:2024\n']

In [8]:
from src.rag import RAG
rag=RAG(db)
rag.ask("which artist sold the most albums?")

{'question': 'which artist sold the most albums?',
 'context': 'artist:Urban Beats\nalbum:City Pulse\nunits_sold:2100.0\nmonth:May\nyear:2023\n\n\nartist:Urban Beats\nalbum:City Pulse\nunits_sold:156.0\nmonth:May\nyear:2023\n\n\nartist:Urban Pulse\nalbum:City Beats\nunits_sold:4100.0\nmonth:May\nyear:2023\n\n\nartist:Urban Pulse\nalbum:City Beats\nunits_sold:295.0\nmonth:May\nyear:2022\n\n\nartist:Urban Pulse\nalbum:City Beats\nunits_sold:1350.0\nmonth:April\nyear:2023\n',
 'answer': 'Answer: Urban Pulse'}